### ISSUE TITLE
Fail on centos

### ISSUE THREAD

**Issue by grasshoppergn** [AnyChart/gjstags#1]
На центоси оно вообще не компилилось, а когда ты компилил его у себя, то при запуски валится это:

[Grasshopper@GreenCentOS Work]$ gjstags -r ./stock-js/src/
Exception in thread "main" java.lang.NoClassDefFoundError: com/google/javascript/jscomp/NodeTraversal$Callback
        at com.anychart.gjstags.CommandLineRunner.main(CommandLineRunner.java:129)
Caused by: java.lang.ClassNotFoundException: com.google.javascript.jscomp.NodeTraversal$Callback
        at java.net.URLClassLoader$1.run(URLClassLoader.java:366)
        at java.net.URLClassLoader$1.run(URLClassLoader.java:355)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.net.URLClassLoader.findClass(URLClassLoader.java:354)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:423)
        at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:308)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:356)
        ... 1 more

**Comment by batsuev** [comment]
Fixed
